carta_homepage:
    path:       /
    defaults:   { _controller: AdminBundle:CartaMenu:index }

carta_save_user:
    path:       /save
    defaults:   { _controller: AdminBundle:CartaMenu:saveUser }
    methods:    [POST]
