mapa_homepage:
    path:       /
    defaults:   { _controller: "AdminBundle:Mapa:index" }

mapa_save:
    path:       /save
    defaults:   { _controller: "AdminBundle:Mapa:save" }
    methods:    [POST]

mapa_current:
    path:       /getCurrent
    defaults:   { _controller: "AdminBundle:Mapa:currentMap" }
    methods:    [GET]

mapa_current_php:
    path:       /getCurrentPhp
    defaults:   { _controller: "AdminBundle:Mapa:currentMapPhp" }
    methods:    [GET]

buscar_servicio:
    path:       /buscarServicio/{id}
    defaults:   { _controller: "AdminBundle:Mapa:buscarServicio" }