frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /Admin

local_comercial:
    resource: "@AdminBundle/Resources/config/localComercial.yml"
    prefix:   /LocalComercial
