# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            pattern:    ^/*
            provider: all
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /Login
            remember_me:
                key:    %secret%
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/LocalComercial, roles: ROLE_LOCAL_COMERCIAL }
        - { path: ^/Admin, roles: ROLE_ADMIN }
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        all:
            chain:
                providers: [admin, usuarios]

        admin:
            memory:
                users:
                    admin: { password: admin, roles: ROLE_ADMIN }
                    local: { password: local, roles: ROLE_LOCAL_COMERCIAL }

        usuarios:
            entity: { class: Tesis\AdminBundle\Entity\Usuario, property: usuario }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Tesis\AdminBundle\Entity\Usuario: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_LOCAL_COMERCIAL: ROLE_USER
