# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            pattern:    ^/*
            provider: users
            anonymous:  ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /Admin
            logout:
                path: logout
                target: /

    access_control:
        - { path: ^/LocalComercial, roles: ROLE_LOCAL }
        - { path: ^/Admin, roles: ROLE_ADMIN }
        - { path: ^/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        users:
            memory:
                users:
                    admin: { password: 1234, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

