imports:
    - { resource: "@AdminBundle/Resources/config/manager.yml" }


services:
    app.twig_extension:
        class: Tesis\FrontendBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }