app_homepage:
    path:     /
    defaults: 
        _controller: FrameworkBundle:Redirect:redirect
        route: informacion_homepage
        permanent: true

informacion:
    resource:   '@FrontendBundle/Resources/config/routing/informacion.yml'
    prefix:     /Informacion