informacion_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Informacion:index }

informacion_edificio:
    path:     /Edificio
    defaults: { _controller: FrontendBundle:Informacion:edificio }

informacion_servicios:
    path: /Servicios
    defaults: { _controller: FrontendBundle:Informacion:servicios }

informacion_servicio_items:
    path: /Servicio/{id}
    defaults: { _controller: FrontendBundle:Informacion:servicioItems }

informacion_item_detalle:
    path: /Servicio/Item/{id}
    defaults: { _controller: FrontendBundle:Informacion:ItemDetalle }

informacion_estoy_en:
    path: /Servicio/Item/{id}/estoy_en
    defaults: { _controller: FrontendBundle:Informacion:estoyEn }

indicaciones:
    path: /Servicio/Item/{id}/indicaciones/{puntoInicio}
    defaults: { _controller: FrontendBundle:Informacion:indicaciones }

informacion_como_llegar:
    path: /ComoLlegar
    defaults: { _controller: FrontendBundle:Informacion:ComoLlegar }

confiterias:
    resource:   '@FrontendBundle/Resources/config/routing/confiterias.yml'
    prefix:     /Confiterias