local_homepage:
    path:   /
    defaults:   { _controller: "AdminBundle:LocalComercial:index" }

local_save_info:
    path:   /Info/Save
    defaults:   { _controller: "AdminBundle:LocalComercial:saveInfo" }
    methods: [POST]

categoria_list:
    path:   /ListadoCategorias
    defaults: { _controller: "AdminBundle:Categoria:list" }
    methods: [GET]

categoria_save:
    path:   /GuardarCategoria
    defaults:   { _controller: "AdminBundle:Categoria:save" }
    methods: [POST]

categoria_remove:
    path:   /EliminarCategoria/{id}
    defaults:   { _controller: "AdminBundle:Categoria:remove" }

producto_save:
    path:   /GuardarProducto
    defaults:   { _controller: "AdminBundle:Producto:save" }
    methods: [POST]

producto_remove:
    path:   /EliminarProducto/{id}
    defaults:   { _controller: "AdminBundle:Producto:remove" }
