admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

info:
    resource:   "@AdminBundle/Resources/config/routing/info.yml"
    prefix:     /Info

mapa:
    resource:   "@AdminBundle/Resources/config/routing/mapa.yml"
    prefix:     /MapaDeRecorridos

cartaMenu:
    resource:   "@AdminBundle/Resources/config/routing/cartaMenu.yml"
    prefix:     /CartaMenu

ubicacion:
    resource:   "@AdminBundle/Resources/config/routing/ubicacion.yml"
    prefix:     /UbicacionDeServicios

servicio:
    resource:   "@AdminBundle/Resources/config/routing/servicio.yml"
    prefix:     /Servicio

servicio_item:
    resource:   "@AdminBundle/Resources/config/routing/servicioItem.yml"
    prefix:     /ServicioItem

servicio_rest:
    type:       rest
    resource:   "Tesis\AdminBundle\Controller\ServicioRestController"
    prefix:     /api

servicio_item_rest:
    type:       rest
    resource:   "Tesis\AdminBundle\Controller\ServicioItemRestController"
    prefix:     /api