services:
    login_listener:
        class: Tesis\AdminBundle\Listener\LoginListener
        arguments: [@router]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
